### ISSUE TITLE
Copy pre-commit config

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/dashboard#12]
- [ ] copy the pre-commit configuration from another project (like https://github.com/packit-service/packit , https://github.com/packit-service/packit-service or https://github.com/packit-service/ogr)
- [ ] try it and tweak if needed

**Comment by ssd71** [comment]
Hello! I would like to work on this

**Comment by SudhanAruna** [comment]
> 
> 
>     * [ ]  copy the pre-commit configuration from another project (like https://github.com/packit-service/packit , https://github.com/packit-service/packit-service or https://github.com/packit-service/ogr)
> 
>     * [ ]  try it and tweak if needed

I added pre commit config file. Any thing i should add?

**Comment by SudhanAruna** [comment]
I added the pre commit configuration file. Any thing i should add?

**Comment by lachmanfrantisek** [comment]
> I added the pre commit configuration file. Any thing i should add?

Thanks. See [the related PR](https://github.com/packit-service/dashboard/pull/14).
