### ISSUE TITLE
Not able to run app.py

### ISSUE THREAD

**Issue by rpotter12** [packit-service/dashboard#15]
Hi
I am a GSoC aspirant. I am looking forward to applying for GSoC in fedora.

I was trying to run app.py and I got this -
![Screenshot from 2020-02-25 17-28-11](https://user-images.githubusercontent.com/34352567/75245704-40432380-57f4-11ea-875c-0f256318f875.png)
![Screenshot from 2020-02-25 17-28-23](https://user-images.githubusercontent.com/34352567/75245722-46390480-57f4-11ea-8db4-2b80b9efbca4.png)

I want to know is app.py is the main entry point of the whole project or some other script is the main entry point?

**Comment by lachmanfrantisek** [comment]
Hi @rpotter12 !

Try using a `run` target from `Makefile`:

```
make run
```

You can see that it actually runs this command:

```
FLASK_ENV=development FLASK_APP=packit_dashboard.app flask-3 run
```

(The `FLASK_APP=packit_dashboard.app` will probably solve your problem.)

**Comment by rpotter12** [comment]
@lachmanfrantisek Thanks :)
