### ISSUE TITLE
Making Makefile on Ubuntu gives error

### ISSUE THREAD

**Issue by ritwickraj78** [packit-service/dashboard#18]
sudo: dnf: command not found
Makefile:5: recipe for target 'install-dependencies' failed
make: *** [install-dependencies] Error 1

![Screenshot from 2020-03-03 04-27-09](https://user-images.githubusercontent.com/43514828/75725934-6b9fa400-5d07-11ea-9bb4-f3faaa5f4234.png)

**Comment by ritwickraj78** [comment]
The dnf command is not recognised by Debian, instead using apt does the job. I hope that should work. @csomh @lachmanfrantisek .

**Comment by ritwickraj78** [comment]
I have locally built just the dashboard on my system to work on it. Will that be an issue ?

**Comment by rishavanand** [comment]
The make file is actually written for Fedora which uses DNF as it's package manager (next gen YUM), if I'm correct.

**Comment by lachmanfrantisek** [comment]
You are right, we use the `dnf` as a package manager -- we can fix this problem by:
- Finding the right package manager.
- Have a variable for that.
- Use some general tool like ansible playbook with [package module](https://docs.ansible.com/ansible/latest/modules/package_module.html).

**Comment by ritwickraj78** [comment]
@lachmanfrantisek Can I take up this issue?

**Comment by ritwickraj78** [comment]
@lachmanfrantisek I have made a PR referencing this issue. If you could please review it.
