### ISSUE TITLE
Setup tests

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/dashboard#21]
- [ ] Create some tests.
- [ ] Setup the directory structure as we have in other projects.
- [ ] Add Makefile target for that.
- [ ] Make the tests in a way we can easily run them in the CI.

**Comment by lachmanfrantisek** [comment]
@IceWreck do you wantto work on it?

**Comment by IceWreck** [comment]
Yes

**Comment by lachmanfrantisek** [comment]
@IceWreck that was qucik..;)

**Comment by IceWreck** [comment]
> @IceWreck that was quick..;)

Yeah I had my email open for homework and saw your message.
