### ISSUE TITLE
Error while try to run on local machine !

### ISSUE THREAD

**Issue by csayaan** [packit-service/dashboard#27]
![Screenshot from 2020-03-22 16-51-46](https://user-images.githubusercontent.com/46599244/77248195-92ddf700-6c5d-11ea-80ed-9ad136c6eae2.png)
What to do ???

**Comment by rishavanand** [comment]
Node modules directory seems to be missing. Can you do a `npm i` and then try again?

**Comment by csayaan** [comment]
Can You help me with the CLI for run this repo into my local machine ?

**Comment by TomasTomecek** [comment]
You're clearly using an older version of python since it doesn't recognize the f-string syntax. All our projects require python3.6+

In Fedora 31 we now have:
```
$ python3 --version                                                                                                                                              
Python 3.7.6
```

**Comment by csayaan** [comment]
I am using Ubuntu 18.04
![Screenshot from 2020-03-23 13-22-44](https://user-images.githubusercontent.com/46599244/77294082-98911680-6d09-11ea-9713-15b2d5c55432.png)

**Comment by lachmanfrantisek** [comment]
As you can see in the logs, you run the app with the Python2.7.

**Comment by csayaan** [comment]
If I do this then this is happening !
![Screenshot from 2020-03-23 13-22-44](https://user-images.githubusercontent.com/46599244/77296216-536ee380-6d0d-11ea-86cb-00537d0940ce.png)

**Comment by csayaan** [comment]
![Screenshot from 2020-03-23 13-50-41](https://user-images.githubusercontent.com/46599244/77296358-87e29f80-6d0d-11ea-9a47-28a20cbba80d.png)

**Comment by csayaan** [comment]
What are the commands for run this app successfully?

**Comment by lachmanfrantisek** [comment]
> What are the commands for run this app successfully?

Try `make run` from the top directory. It should call right `flask` ( = `flask-3`) and make the imports work.

**Comment by TomasTomecek** [comment]
> What are the commands for run this app successfully?

Run it with python 3.6+

We have a make target to run it in a local environment:
```
run:
	FLASK_ENV=development FLASK_APP=packit_dashboard.app flask-3 run
```

Feel free to override the command if flask-3 executable is not available on your system.

**Comment by csayaan** [comment]
It works.. Thank you very much @TomasTomecek , @lachmanfrantisek  for your great support.
Should I update the README file with the installation guide ? or we can do it later ?

**Comment by lachmanfrantisek** [comment]
> Should I update the README file with the installation guide ? o

If you find some info that can be relevant to others, create a PR with that. Thanks

**Comment by csayaan** [comment]
Ok , Thanks.
