### ISSUE TITLE
Update description of this repo

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/dashboard#28]
Our README is pretty basic, can we get some more text in there?

**Comment by csayaan** [comment]
> Our README is pretty basic, can we get some more text in there?
I can update it with the installation guide.

**Comment by TomasTomecek** [comment]
yup, go ahead

**Comment by devarshigoswami** [comment]
If this issue isn't resolved yet, can I have a go?

**Comment by lachmanfrantisek** [comment]
> If this issue isn't resolved yet, can I have a go?

It is being fixed by https://github.com/packit-service/dashboard/pull/31
