### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/dashboard#29]
...and describe how to run dashboard locally and in a container

**Comment by rishavanand** [comment]
I can take this up. I'll pickup the template from packit-service repo and make modifications as needed. Will discuss the missing parts here.

**Comment by TomasTomecek** [comment]
awesome, thank you!

**Comment by devarshigoswami** [comment]
If this task has not been resolved, can I work on it?

**Comment by lachmanfrantisek** [comment]
> If this task has not been resolved, can I work on it?

I've already assigned @rishavanand so we are expecting a pull-request from him. If you want to contribute, look at the other issues here or [in the packit-service repository](https://github.com/packit-service/packit-service/issues)...
